# Generated by Django 5.1.3 on 2024-11-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="owner",
        ),
    ]
