# Generated by Django 5.1.3 on 2024-11-19 17:12

import django.db.models.deletion
import likes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0002_remove_like_user_like_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="owner",
            field=models.ForeignKey(
                default=likes.models.get_default_owner,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]



